### ISSUE TITLE
Make Step Variable public

### ISSUE THREAD

**Issue by vinced45** [Swiftification/StepFlow#1]
Could you make the Steps variable public so we could append steps for a dynamic amount of steps?

**Comment by JARMourato** [comment]
@vinced45 I could do that. Is your intention to add Steps dynamically with the flow running ? because Steps are removed from the array as the Flow executes.

**Comment by vinced45** [comment]
I think what I can do is just create my [Step] array and pass that to the init. That should work. I'll close this but thanks for the quick reply.
